#%RAML 1.0 Trait
responses:
  400:
    body:
      application/json:
        example: !include ../examples/400ErrorExample.raml
  401:
    body:
      application/json:
        example: !include ../examples/401ErrorExample.raml
  404:
    body:
      application/json:
        example: !include ../examples/404ErrorExample.raml
  408:
    body:
      application/json:
        example: !include ../examples/408ErrorExample.raml
  422:
    body:
      application/json:
        example: !include ../examples/422ErrorExample.raml
  500:
    body:
      application/json:
        example: !include ../examples/500ErrorExample.raml
  503:
    body:
      application/json:
        example: !include ../examples/503ErrorExample.raml
          
          