[{
  "employeeId":1000,
  "employeeName":"anil",
  "salary":"45000",
  "phone":"9502628982",
  "email":"anil@gmail.com",
  "department":"MuleSoft"
},
{
  "employeeId":1001,
  "employeeName":"kumar",
  "salary":"70000",
  "phone":"9618398497",
  "email":"kumar@gmail.com",
  "department":"MuleSoft"
}]